# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (everyday at midnight CST)
  schedule: [{cron: "6 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: BabyBoySnow
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago

          #achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          #Recent Activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all

          #Discussion followup
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: base, repositories, history

          #Coding Habits
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          #Intro
          plugin_introduction: yes
          plugin_introduction_title: yes

          #Coding commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          #Languages used
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          #Lines changed overtime
          plugin_lines: yes
          plugin_lines_delay: 5
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base, repositories, history

          #Music
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/playlist/47r4IpO61ercoZlHnRta6n
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: gzfkm11r0c3ib3w28ed7i2hze

          #resp
          plugin_repositories: yes
          plugin_repositories_featured: ClearVision/ClearVision-v6, Just-Some-Bots/MusicBot
          plugin_repositories_order: featured, pinned, starred, random

          #Steam
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_KEY }}
          plugin_steam_achievements_limit: 5
          plugin_steam_games_limit: 3
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 5
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: 76561198428584656

          #Include forks
          repositories_forks: yes